package vista;

import controlador.LoginC;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author marce
 */
public class LoginV extends javax.swing.JFrame {

    /**
     * Creates new form LoginV
     */
    public LoginV() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LoginVSalir = new javax.swing.JButton();
        LoginVUsuario = new javax.swing.JTextField();
        LoginVIngresar = new javax.swing.JButton();
        LoginVPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido a GestionProject");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 340, 40));

        LoginVSalir.setBackground(new java.awt.Color(153, 153, 153));
        LoginVSalir.setText("Salir");
        LoginVSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginVSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginVSalirMouseExited(evt);
            }
        });
        LoginVSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginVSalirActionPerformed(evt);
            }
        });
        LoginVSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginVSalirKeyPressed(evt);
            }
        });
        jPanel2.add(LoginVSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 0, -1, 30));

        LoginVUsuario.setForeground(new java.awt.Color(153, 153, 153));
        LoginVUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginVUsuario.setText("Ingresar Usuario");
        LoginVUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginVUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginVUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginVUsuarioMouseExited(evt);
            }
        });
        LoginVUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginVUsuarioActionPerformed(evt);
            }
        });
        LoginVUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginVUsuarioKeyPressed(evt);
            }
        });
        jPanel2.add(LoginVUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 220, -1));

        LoginVIngresar.setBackground(new java.awt.Color(255, 255, 255));
        LoginVIngresar.setText("Ingresar");
        LoginVIngresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginVIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginVIngresarActionPerformed(evt);
            }
        });
        LoginVIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginVIngresarKeyPressed(evt);
            }
        });
        jPanel2.add(LoginVIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 90, -1));

        LoginVPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginVPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginVPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginVPasswordKeyPressed(evt);
            }
        });
        jPanel2.add(LoginVPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 220, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginVSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginVSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_LoginVSalirActionPerformed

    private void LoginVSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginVSalirMouseEntered
        LoginVSalir.setBackground(Color.red);
    }//GEN-LAST:event_LoginVSalirMouseEntered

    private void LoginVSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginVSalirMouseExited
        LoginVSalir.setBackground(Color.gray);
    }//GEN-LAST:event_LoginVSalirMouseExited

    private void LoginVUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginVUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginVUsuarioActionPerformed

    private void LoginVUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginVUsuarioMouseEntered
        if(LoginVUsuario.getText().equals("Ingresar Usuario")){LoginVUsuario.setText(""); LoginVUsuario.setForeground(Color.black);}
    }//GEN-LAST:event_LoginVUsuarioMouseEntered

    private void LoginVUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginVUsuarioMouseExited
        if(LoginVUsuario.getText().equals("")){LoginVUsuario.setText("Ingresar Usuario"); LoginVUsuario.setForeground(Color.gray);}
    }//GEN-LAST:event_LoginVUsuarioMouseExited

    private void LoginVUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginVUsuarioKeyPressed
          if(LoginVUsuario.getText().equals("Ingresar Usuario")){LoginVUsuario.setText("");LoginVUsuario.setForeground(Color.black);}
          if(evt.getKeyCode() == KeyEvent.VK_ENTER){var validar = new LoginC(LoginVUsuario.getText(),LoginVPassword.getText());
            if(validar.consultarUser()){System.exit(0);}}
    }//GEN-LAST:event_LoginVUsuarioKeyPressed

    private void LoginVIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginVIngresarKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){var validar = new LoginC(LoginVUsuario.getText(),LoginVPassword.getText());
       if(validar.consultarUser()){System.exit(0);}}
    }//GEN-LAST:event_LoginVIngresarKeyPressed

    private void LoginVSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginVSalirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){System.exit(0);}
    }//GEN-LAST:event_LoginVSalirKeyPressed

    private void LoginVIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginVIngresarActionPerformed
        var validar = new LoginC(LoginVUsuario.getText(),LoginVPassword.getText());
        if(validar.consultarUser()){System.exit(0);}
    }//GEN-LAST:event_LoginVIngresarActionPerformed

    private void LoginVPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginVPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){var validar = new LoginC(LoginVUsuario.getText(),LoginVPassword.getText());
           if(validar.consultarUser()){System.exit(0);}}
    }//GEN-LAST:event_LoginVPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginVIngresar;
    private javax.swing.JPasswordField LoginVPassword;
    private javax.swing.JButton LoginVSalir;
    private javax.swing.JTextField LoginVUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
